// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq-zLHY_6a8c--0wZoAip6VNPr3HOw04A',
    appId: '1:694199539541:web:48501578da85c6fb9d01dc',
    messagingSenderId: '694199539541',
    projectId: 'projeto1-ifrs-9234b',
    authDomain: 'projeto1-ifrs-9234b.firebaseapp.com',
    storageBucket: 'projeto1-ifrs-9234b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkMYb15vcmyLNdO6ZXcRxtarLIWwgt3hw',
    appId: '1:694199539541:android:151b99ee21c6a9889d01dc',
    messagingSenderId: '694199539541',
    projectId: 'projeto1-ifrs-9234b',
    storageBucket: 'projeto1-ifrs-9234b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqmZKXQGTG2AVro6uL12tNRNqUB-oP9qs',
    appId: '1:694199539541:ios:8235a14ef5df23f49d01dc',
    messagingSenderId: '694199539541',
    projectId: 'projeto1-ifrs-9234b',
    storageBucket: 'projeto1-ifrs-9234b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqmZKXQGTG2AVro6uL12tNRNqUB-oP9qs',
    appId: '1:694199539541:ios:8235a14ef5df23f49d01dc',
    messagingSenderId: '694199539541',
    projectId: 'projeto1-ifrs-9234b',
    storageBucket: 'projeto1-ifrs-9234b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq-zLHY_6a8c--0wZoAip6VNPr3HOw04A',
    appId: '1:694199539541:web:4f8e98ed6ec1f0649d01dc',
    messagingSenderId: '694199539541',
    projectId: 'projeto1-ifrs-9234b',
    authDomain: 'projeto1-ifrs-9234b.firebaseapp.com',
    storageBucket: 'projeto1-ifrs-9234b.firebasestorage.app',
  );

}